const A=document.getElementById('app');
function trackEvent(name,params){if(typeof gtag==='function')gtag('event',name,params||{});}
let S={screen:'home',exam:null,type:null,i:null,sec:0,timer:null,paused:false,answer:'',result:null};
const names={ibps:{essay:'Essay Writing',comprehension:'Comprehension'},sbi:{email:'Email Writing',situation:'Situation Analysis',report:'Report Writing',precis:'Precis Writing',full:'Full Descriptive'}};
const meta={ibps:{title:'IBPS PO / MT-XVI',total:25,time:30},sbi:{title:'SBI PO 2026',total:30,time:30}};
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function stop(){clearInterval(S.timer);S.timer=null}
function reset(){stop();S={screen:'home',exam:null,type:null,i:null,sec:0,timer:null,paused:false,answer:'',result:null};render()}
function home(){reset()}
function exitTest(){if(S.result){types();return}const old=document.getElementById('exit-notice');if(old)old.remove();const modal=document.createElement('div');modal.id='exit-notice';modal.style.cssText='position:fixed;inset:0;background:rgba(20,18,30,.52);display:flex;align-items:center;justify-content:center;padding:20px;z-index:9999;backdrop-filter:blur(5px)';modal.innerHTML='<div style="width:min(440px,100%);background:#fff;border-radius:22px;padding:30px;box-shadow:0 24px 70px rgba(0,0,0,.25);text-align:center"><div style="font-size:2.2rem;margin-bottom:8px">⚠️</div><p class="eyebrow" style="margin-bottom:8px">Leave this test?</p><h2 style="margin:0 0 10px">Are you sure you want to exit?</h2><p class="muted" style="margin:0 auto 22px;line-height:1.65">Your current answer and timer progress will be lost if you leave this test.</p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><button class="secondary" onclick="document.getElementById(\'exit-notice\')?.remove()">Stay in test</button><button class="primary" onclick="document.getElementById(\'exit-notice\')?.remove();stop();trackEvent(\'test_exit_confirmed\',{exam:S.exam,section:S.type,test_number:S.i+1});S.screen=\'tests\';render()">Exit test</button></div></div>';document.body.appendChild(modal)}
function choose(e){stop();S.exam=e;S.screen='types';render()}
function types(){stop();S.screen='types';render()}
function openType(t){stop();S.type=t;S.screen='tests';render()}
function data(){return SF[S.exam][S.type]||[]}
function render(){if(S.screen==='home')homeView();else if(S.screen==='types')typeView();else if(S.screen==='tests')testList();else if(S.screen==='test')testView();else if(S.screen==='patterns')patternsView();else if(S.screen==='scores')scoreInfoView()}
function homeView(){A.innerHTML=`<section class="hero"><p class="eyebrow">Free PO descriptive practice · no login</p><h1>Write better.<br>Practice smarter.</h1><p class="lead">Practice reported questions separately from original practice, track your word count, get a transparent practice score and learn what to improve.</p><div class="hero-actions"><button class="primary" onclick="choose('ibps')">Practice IBPS PO →</button><button class="secondary" onclick="choose('sbi')">Practice SBI PO →</button></div></section><div class="section-title"><div><p class="eyebrow">Choose your exam</p><h2>Build exam-ready writing habits</h2></div><button class="ghost" onclick="patterns()">View official pattern →</button></div><div class="grid"><div class="card"><span class="badge">IBPS PO / MT-XVI</span><h2>Essay + Comprehension</h2><p class="muted">2 practice sections · 50 tests in each section.</p><div class="stat-row"><span class="stat">Essay · 50</span><span class="stat">Comprehension · 50</span></div><button class="primary" onclick="choose('ibps')">Open IBPS sections</button></div><div class="card"><span class="badge coral">SBI PO 2026</span><h2>Communication Skills</h2><p class="muted">5 practice sections · 50 tests in each section.</p><div class="stat-row"><span class="stat">Email · 50</span><span class="stat">Situation · 50</span></div><button class="primary" onclick="choose('sbi')">Open SBI sections</button></div></div><div class="notice" style="margin-top:18px"><b>Integrity first:</b> reported questions are labelled <b>Reported PYQ</b>. Original prompts are labelled <b>Practice</b>. SCOREFREE never presents an original prompt as a PYQ.</div>`}
function typeView(){let keys=Object.keys(names[S.exam]);A.innerHTML=`<button class="back" onclick="home()">← Back</button><p class="eyebrow">${meta[S.exam].title}</p><h1 style="font-size:clamp(2.4rem,6vw,4.6rem)">Choose a skill.</h1><p class="lead">Every section below contains exactly <b>50 tests</b>. The number of reported PYQs is intentionally not shown here so the 50-test practice bank is clear.</p><div class="types">${keys.map(k=>{let d=SF[S.exam][k];return `<div class="card type"><div><span class="badge ${k==='precis'||k==='report'?'coral':''}">${names[S.exam][k]}</span><h3>50 tests</h3><div class="count">50-test practice bank</div></div><button class="primary" onclick="openType('${k}')">Open 50 tests →</button></div>`}).join('')}</div>`}
function testList(){let d=data();A.innerHTML=`<button class="back" onclick="types()">← Back to ${meta[S.exam].title}</button><p class="eyebrow">${meta[S.exam].title}</p><h1 style="font-size:clamp(2.2rem,5vw,4.3rem)">${names[S.exam][S.type]}</h1><p class="lead"><b>50 tests.</b> Pick any test. For IBPS Comprehension, the full reading passage appears on the test page before the question. You will also see the word-limit status and a topic-specific learning guide before you write.</p><div class="notice"><b>Official vs practice limits:</b> The current official 2026 notifications do not publish universal fixed word limits for these descriptive tasks. SCOREFREE therefore labels every suggested range as a <b>practice target</b>, not an official limit. Précis follows the SBI training guidance of normally one-third of the source passage, unless the question says otherwise.</div><div class="tests">${d.map((q,i)=>`<button class="test" onclick="start(${i})"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="tag ${q[0]==='PYQ'?'pyq':'practice'}">${q[0]==='PYQ'?'Reported PYQ':'Practice'}</span><span class="small">${esc(q[1])} · ${esc(q[2]).slice(0,95)}${q[2].length>95?'…':''}</span></button>`).join('')}</div>`}
function maxMarks(){if(S.exam==='ibps'&&S.type==='essay')return 15;if(S.exam==='ibps'&&S.type==='comprehension')return 10;if(S.exam==='sbi'&&['email','precis','report','situation'].includes(S.type))return 10;if(S.exam==='sbi'&&S.type==='full')return 30;return 10}
function practiceSeconds(){return S.exam==='sbi'?600:900}
function start(i){S.i=i;S.answer='';S.result=null;S.screen='test';S.sec=practiceSeconds();S.paused=false;render();clock()}
function clock(){stop();S.timer=setInterval(()=>{if(!S.paused){S.sec--;update()}if(S.sec<=0){S.sec=0;stop();let st=document.getElementById('status');if(st)st.textContent='Time is up — submit when ready.'}},1000)}
function update(){let x=document.getElementById('timer');if(x){x.textContent=fmt(S.sec);x.classList.toggle('warn',S.sec<=120)}}
function pause(){S.paused=!S.paused;let b=document.getElementById('pause');if(b)b.textContent=S.paused?'▶ Resume':'⏸ Pause';let st=document.getElementById('status');if(st)st.textContent=S.paused?'Timer paused':'You can submit before the timer ends.'}
function count(){let a=document.getElementById('answer');if(!a)return;S.answer=a.value;let w=document.getElementById('wc');if(w)w.textContent=wordCount(S.answer)}
function wordCount(s){return String(s||'').trim()?String(s).trim().split(/\s+/).length:0}
function wordRule(){if(S.exam==='sbi'&&S.type==='precis')return {title:'Official SBI training guidance',text:'Normally one-third of the source passage. Follow the exact word limit stated in the question.'};return {title:'Official 2026 word-limit status',text:'No universal fixed word limit is published in the current official 2026 notification for this task. Follow the word limit stated in the actual question.'}}
function practiceTarget(){if(S.exam==='ibps'&&S.type==='essay')return 'Practice target: 250–300 words (not an official IBPS 2026 limit).';if(S.exam==='ibps'&&S.type==='comprehension')return 'Practice target: 80–100 words (not an official IBPS 2026 limit).';if(S.exam==='sbi'&&S.type==='email')return 'Practice target: 120–150 words (not an official SBI 2026 limit).';if(S.exam==='sbi'&&S.type==='situation')return 'Practice target: 150–180 words (not an official SBI 2026 limit).';if(S.exam==='sbi'&&S.type==='report')return 'Practice target: 180–220 words (not an official SBI 2026 limit).';if(S.exam==='sbi'&&S.type==='precis')return 'Follow the précis instruction: normally about one-third of the source passage, unless the question gives a different limit.';return 'Practice target: use the task-specific range shown in this question; these ranges are practice guidance, not official exam limits.'}
function promptText(q){let base=esc(q[3]||'');let target;if(S.exam==='sbi'&&S.type==='precis'&&q[5]){let n=wordCount(q[5]);target=`Practice target: about one-third of this ${n}-word passage (~${Math.round(n/3)} words). This is guidance, not a universal SBI 2026 notification limit.`}else target=practiceTarget();return `${base}<br><span class="practice-target">${esc(target)}</span>`}
function passageHtml(q){if(!q[5])return '';if(S.exam==='ibps'&&S.type==='comprehension')return `<div class="passage"><div class="passage-label">Reading passage</div><p>${esc(q[5])}</p></div>`;if(S.exam==='sbi'&&S.type==='precis')return `<div class="passage"><div class="passage-label">Passage to précis</div><p>${esc(q[5])}</p></div>`;return ''}
function criteria(){if(S.exam==='ibps')return ['Relevance & development','Organisation & flow','Reasoning / evidence','Language & clarity'];if(S.type==='email')return ['Purpose & relevance','Professional format','Action / completeness','Language & tone'];if(S.type==='situation')return ['Issue identification','Judgement & ethics','Action plan','Clarity & tone'];if(S.type==='report')return ['Report structure','Facts / findings','Recommendations','Language & clarity'];if(S.type==='precis')return ['Central idea','Coverage','Concision','Language'];return ['Task completion','Structure','Relevance','Language']}
function evaluate(q,answer){const text=String(answer||'').trim(),w=wordCount(text),p=[q[2]||'',q[3]||'',q[4]||''].join(' '),lower=text.toLowerCase();let stopWords=new Set('about after again against all also and any are because been before being between but can could did does doing for from had has have how into its more most much must not now of on one only or other our out over should some such than that their them then there these they this those through to under very was were what when where which while who why will with would you your'.split(' '));let keywords=(p.toLowerCase().match(/[a-z]{5,}/g)||[]).filter((v,i,a)=>!stopWords.has(v)&&a.indexOf(v)===i).slice(0,18);let hits=keywords.filter(k=>lower.includes(k)).length;let relevance=Math.min(100,Math.round((hits/Math.max(4,Math.min(8,keywords.length)))*100));let sentences=text?text.split(/[.!?]+/).filter(x=>x.trim()).length:0;let paras=text?text.split(/\n\s*\n/).filter(x=>x.trim()).length:0;let structure=Math.min(100,Math.round((paras>=3?45:paras>=2?35:sentences>=4?25:10)+(sentences>=4?25:sentences>=2?15:5)+(/[,:;]/.test(text)?15:0)+(/^(subject|to|from|dear|title|report)/im.test(text)?15:0)));let avg=sentences?w/sentences:0;let language=Math.min(100,Math.round((sentences>=4?35:sentences>=2?20:8)+(avg>=8&&avg<=30?30:15)+(/\b(the|and|but|because|however|therefore|also)\b/i.test(text)?15:5)+(/[A-Z][^.!?]*[.!?]/.test(text)?15:5)));let completeness=Math.min(100,Math.round((w>=80?35:w>=40?20:w>0?10:0)+(sentences>=3?25:sentences>=1?10:0)+(paras>=2?20:0)+(w>0?20:0)));let total=Math.round(relevance*.25+structure*.25+language*.25+completeness*.25);if(!text)total=0;if(relevance<20)total=Math.round(total*(relevance/100));let marks=Math.round((total*maxMarks()/100)*10)/10;return {total,marks,max:maxMarks(),breakdown:[relevance,structure,language,completeness],words:w}}
function topicGuide(q){return (q[4]||'').split(/\s*;\s*/).filter(Boolean)}
function testView(){let q=data()[S.i];let content=S.result?resultView(q,S.result):`<div class="prompt"><div class="prompttext"><span class="tag ${q[0]==='PYQ'?'pyq':'practice'}">${q[0]==='PYQ'?'Reported PYQ':'Original Practice'}</span><p class="small">${esc(q[1])}</p><h2>${esc(q[2])}</h2><p>${promptText(q)}</p>${passageHtml(q)}<div class="learn-strip"><div><b>🎯 Topic learning guide</b><span>${esc(q[4]||'Build your response around the exact task, use relevant points and finish with a clear conclusion or action.')}</span></div><div class="word-rule"><b>📏 ${wordRule().title}</b><span>${wordRule().text}</span></div></div><div class="answerbox"><textarea id="answer" class="textarea" placeholder="Type your answer here…" oninput="count()">${esc(S.answer)}</textarea><div class="words"><span id="wc">${wordCount(S.answer)}</span> words</div></div></div></div><div class="actions"><button class="secondary" id="pause" onclick="pause()">⏸ Pause</button><button class="primary" onclick="submit()">Submit & score →</button></div><p class="small" id="status" style="text-align:right">You can submit before the timer ends.</p>`;A.innerHTML=`<div style="max-width:960px;margin:auto"><button class="back" onclick="exitTest()">← Exit test</button><div class="testhead"><div><p class="eyebrow">${meta[S.exam].title} · ${names[S.exam][S.type]}</p><h2>Test ${String(S.i+1).padStart(2,'0')} <span class="small">of 50</span></h2><span class="small">${q[0]==='PYQ'?'Reported PYQ':'Original practice'} · ${S.exam==='sbi'?'10-minute':'15-minute'} focused practice</span></div><div class="timerbox"><div class="timer" id="timer">${fmt(S.sec)}</div><div class="small" id="status">${S.paused?'Timer paused':''}</div></div></div>${content}</div>`;if(S.result)stop();else{let a=document.getElementById('answer');if(a){a.focus();a.setSelectionRange(a.value.length,a.value.length)}}}
function submit(){let a=document.getElementById('answer');S.answer=a?a.value:S.answer;stop();S.result=evaluate(data()[S.i],S.answer);trackEvent('test_submitted',{exam:S.exam,section:S.type,test_number:S.i+1,score:S.result.marks,max_marks:S.result.max,practice_score_100:S.result.total,word_count:S.result.words});saveResult();render()}
function resultView(q,r){let labels=criteria();let ratio=r.total;return `<div class="feedback"><div class="scorecard"><p class="eyebrow">Practice score</p><div class="scorebig"><span>${r.marks}</span><span class="score-denom">/ ${r.max}</span></div><div class="scorebar"><div class="scorefill" style="width:${ratio}%"></div></div><p class="muted">${r.breakdown[0]<20?"Answer not relevant to the question — topic-specific guidance is hidden.":scoreMessage(ratio)} · ${r.words} words typed</p><div class="rubric">${labels.map((label,i)=>`<div><div class="rubric-row"><span><b>${label}</b></span><span>${r.breakdown[i]}%</span></div><div class="mini-bar"><div class="mini-fill" style="width:${r.breakdown[i]}%"></div></div></div>`).join('')}</div><p class="score-note" style="margin-top:17px">This is a transparent SCOREFREE practice estimate. It is not an official IBPS/SBI examiner score.</p></div><div class="learncard" style="${r.breakdown[0]<20?'display:none':''}"><p class="eyebrow">Solution & learning pointers</p><h3>${esc(q[2])}</h3><p><b>What this topic needs:</b> ${esc(q[4]||'Stay directly focused on the task and cover every requested element.')}</p><ul><li>Start with the main issue, purpose or central idea instead of a generic introduction.</li><li>Develop 2–4 specific points relevant to the topic.</li><li>Use examples, facts or reasoning where the task calls for them.</li><li>End with a clear conclusion, recommendation, request or inference as appropriate.</li><li>Proofread grammar, spelling, tone and required format before submitting.</li></ul><div class="notice" style="margin-top:15px"><b>Word-limit check:</b> ${wordRule().text}<br><b>For this practice:</b> ${practiceTarget()}</div><div class="result-actions"><button class="primary" onclick="retry()">Try again</button><button class="secondary" onclick="openType('${S.type}')">More ${names[S.exam][S.type]}</button></div></div></div>`}
function scoreMessage(p){return p>=85?'Strong attempt':p>=70?'Good base — polish the weak areas':p>=50?'Decent start — work on structure and relevance':'Needs more practice — focus on the learning guide first'}
function retry(){S.result=null;S.answer='';S.sec=practiceSeconds();S.paused=false;render();clock()}
function patterns(){stop();S.screen='patterns';render()}
function patternsView(){A.innerHTML=`<button class="back" onclick="home()">← Back</button><p class="eyebrow">Official 2026 pattern</p><h1 style="font-size:clamp(2.5rem,6vw,4.7rem)">Know the paper.</h1><div class="pattern-grid"><div class="pattern-card"><span class="badge">IBPS PO / MT-XVI</span><h2>Descriptive Paper</h2><p>Essay + Comprehension · 2 questions · <b>25 marks</b> · <b>30 minutes</b> · English.</p><div class="stat-row"><span class="stat">Current 2026 notification</span><span class="stat">No universal 2026 word limit published</span></div></div><div class="pattern-card"><span class="badge coral">SBI PO 2026</span><h2>Communication Skills</h2><p>Emails (1 of 2), Situation Analysis (1 of 2), and either Reports or Precis (1 of 2) · <b>30 marks</b> · <b>30 minutes</b> · English.</p><div class="stat-row"><span class="stat">3 responses</span><span class="stat">Official 2026 advertisement</span></div></div></div><div class="notice" style="margin-top:18px"><b>Word-limit policy:</b> the current official 2026 IBPS PO/MT-XVI and SBI PO 2026 notifications do not publish a universal fixed word limit for these descriptive tasks. SCOREFREE does not invent one. Follow the limit stated in the actual question. For précis, official SBI training guidance says it is normally one-third of the source passage, subject to the question's instruction.</div><div class="section-title"><div><p class="eyebrow">Scoring</p><h2>Learn, don't fake an official score</h2></div></div><div class="card"><p class="muted">Banks publish marks, duration and task structure, but not a public item-by-item writing formula. SCOREFREE therefore uses a transparent <b>practice score out of 100</b> based on relevance, structure, language and completeness. It is not an official examiner score.</p></div>`}
function aboutScores(){S.screen='scores';stop();render()}
function scoreInfoView(){A.innerHTML=`<button class="back" onclick="home()">← Back</button><p class="eyebrow">Transparent evaluation</p><h1 style="font-size:clamp(2.5rem,6vw,4.6rem)">Score it. Learn from it.</h1><div class="grid"><div class="card"><h2>Relevance</h2><p class="muted">Did you address the actual task and include useful, topic-specific points?</p></div><div class="card"><h2>Structure</h2><p class="muted">Is the response easy to follow, with the appropriate format and logical flow?</p></div><div class="card"><h2>Language</h2><p class="muted">Are sentences clear, professional and reasonably accurate?</p></div><div class="card"><h2>Completeness</h2><p class="muted">Did you cover the requested elements and develop the response enough to be useful?</p></div></div><div class="notice" style="margin-top:18px"><b>Important:</b> this score is a SCOREFREE learning estimate shown against the practice section's maximum marks. It is not an official IBPS/SBI marking formula.</div>`}
function saveResult(){let key='sf-history';let old=JSON.parse(localStorage.getItem(key)||'[]');old.unshift({date:new Date().toLocaleString(),exam:S.exam,type:S.type,test:S.i+1,score:S.result.marks,max:S.result.max,practiceScore100:S.result.total});localStorage.setItem(key,JSON.stringify(old.slice(0,20)))}
render();
